package com.github.hugovallada.errors.customErrors

class AlreadyFollowingException(msg: String) : RuntimeException(msg)
